- name: Check barman_state variable
  vars:
    allowed_values: ["started", "absent", "purged"]
  fail:
    msg: 'barman_state allowed values: {{ allowed_values | join(", ") }}'
  when: barman_state is not in allowed_values

- include_tasks: "{{ barman_state }}.yml"
