---
- name: Check Config
  ansible.builtin.include_tasks: check-config.yml

- name: Install
  ansible.builtin.include_tasks: install.yml

- name: Configure
  ansible.builtin.include_tasks: configure.yml

- name: Cron
  ansible.builtin.include_tasks: cron.yml

- name: Telegraf
  ansible.builtin.include_tasks: telegraf.yml
